spring:
    #数据源配置
    datasource:
        #商品库配置(逻辑名称)
        product:
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/ec_product?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true&useCursorFetch=true
    #shardingjdbc数据源配置
    shardingsphere:
        #数据源
        datasource:
            orderds0:
                username: root
                password: 123456
                jdbc-url: jdbc:mysql://127.0.0.1:3306/ec_order_0?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true&useCursorFetch=true
            orderds1:
                username: root
                password: 123456
                jdbc-url: jdbc:mysql://127.0.0.1:3306/ec_order_1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true&useCursorFetch=true
